In [1]:
# qns 7

In [55]:
import numpy as np

In [56]:
old = np.array([[1,1,1],[1,1,1]])

In [57]:
new = old
new[0,:2] = 0
print(old)


[[0 0 1]
 [1 1 1]]


In [58]:
# qns 8

In [59]:
new = old.copy()
new[0,:2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [60]:
# qns 3

In [61]:
import numpy
sampleArray = numpy.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


In [62]:
subArrays = numpy.split(sampleArray, 4) 
print(subArrays)

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [63]:
# qns 4

In [64]:
import numpy
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print(sampleArray)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


In [65]:
newArray = sampleArray[::2, 1::2]
print(newArray)

[[ 6 12]
 [30 36]
 [54 60]]


In [66]:
# qns 2

In [67]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [68]:
minOfAxisOne = numpy.amin(sampleArray, 1) 
print(minOfAxisOne)

[34 12 53]


In [69]:
maxOfAxisOne = numpy.amax(sampleArray, 0) 
print(maxOfAxisOne)

[82 94 73]


In [70]:
# qns 1a

In [71]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [72]:
# 1b

In [73]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [74]:
# qns 1(c)

In [75]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# qns 1(c)

In [77]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# 1f

In [42]:
mat[4]

array([21, 22, 23, 24, 25])

In [45]:
# 1d

In [46]:
mat[3][4]

20

In [51]:
# 1e

In [52]:
mat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [53]:
# 1g

In [54]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
# qns 6

In [1]:
import numpy as np

arr = np.array([[0,1, 2, 3, 4, 5], [6, 7, 8, 9, 10,11],[12,13,14,15,16,17],[18,19,20,21,22,23],[24,25,26,27,28,29],[30,31,32,33,34,35]])
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [22]:
print(arr[2:4, 2:4])

[[14 15]
 [20 21]]


In [29]:
# qns 5

In [53]:
arr.diagonal()


array([ 0,  7, 14, 21, 28, 35])