In [ ]:
### Which of the following command will not create Series object?Select one:a.pd. Series([1,3,5],3,5)b.pd. Series([[1,3,5]])c.pd. Series([1,3,5],[3,5])d.pd. Series([1,3,5])

In [6]:
import pandas as pd
import numpy as np

In [7]:
x = np.arange(20).reshape(4,5)

In [8]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
x[2:4,3:5] + 100

array([[113, 114],
       [118, 119]])

In [10]:
purchase_1 = pd.Series({'Name': 'Rohit',  'Item Purchased': 'Dog Food', 'Cost': 220.50})

purchase_2 = pd.Series({'Name': 'Naaya',  'Item Purchased': 'Kitty Litter', 'Cost': 120.50})

purchase_3 = pd.Series({'Name': 'Vinod',  'Item Purchased': 'Bird See', 'Cost': 50.00})

In [22]:
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 2', 'Store 3'])

In [23]:
df

Name Item Purchased   Cost
Store 1  Rohit       Dog Food  220.5
Store 2  Naaya   Kitty Litter  120.5
Store 3  Vinod       Bird See   50.0

In [25]:
df['Cost'] = df['Cost']*0.8



In [26]:
df

Name Item Purchased   Cost
Store 1  Rohit       Dog Food  176.4
Store 2  Naaya   Kitty Litter   96.4
Store 3  Vinod       Bird See   40.0

In [30]:
np.array([2,2]).dtype


dtype('int32')

In [31]:
np.array([2,'2']).dtype

dtype('<U11')

In [29]:
np.array([2,2.0]).dtype

dtype('float64')

In [32]:
x = np.array([0,1,2,3,4,5])
y = x[0:4]
y[1] = 20

In [33]:
x[1]

20

In [34]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [35]:
arr[3:8]

array([4, 5, 6, 7, 8])

In [36]:
s = pd.Series([1,2,3,4,5])

In [39]:
s[-1]

KeyError: -1

In [40]:
.read_csv(squeeze=false) 

SyntaxError: invalid syntax (<ipython-input-40-4ba670a6638d>, line 1)

In [44]:
s = pd.Series([1,2,3,4,5])

In [45]:
s[0:2]


0    1
1    2
dtype: int64

In [46]:
s = pd.Series([1,2,3,4,5])

In [47]:
max(s)


5

In [48]:
sorted(s)[-1]


5

In [49]:
sorted(s)[4]


5

In [50]:
sorted(s)[0]

1

In [51]:
pd. Series([1,3,5],3,5)


TypeError: Index(...) must be called with a collection of some kind, 3 was passed

In [52]:
pd. Series([[1,3,5]])


0    [1, 3, 5]
dtype: object

In [55]:
pd. Series([1,3,5],[3,5])


ValueError: Length of passed values is 3, index implies 2.

In [54]:

pd. Series([1,3,5])

0    1
1    3
2    5
dtype: int64

In [56]:
purchase_1 = pd.Series({'Name': 'Rohit',  'Item Purchased': 'Dog Food', 'Cost': 220.50})

purchase_2 = pd.Series({'Name': 'Naaya',  'Item Purchased': 'Kitty Litter', 'Cost': 120.50})

purchase_3 = pd.Series({'Name': 'Vinod',  'Item Purchased': 'Bird See', 'Cost': 50.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 2', 'Store 3'])

In [57]:
df

Name Item Purchased   Cost
Store 1  Rohit       Dog Food  220.5
Store 2  Naaya   Kitty Litter  120.5
Store 3  Vinod       Bird See   50.0

In [58]:

df[df['Name']>70]]


SyntaxError: unmatched ']' (<ipython-input-58-8848a4da59d7>, line 1)

In [59]:

df[df['Cost']>70]


Name Item Purchased   Cost
Store 1  Rohit       Dog Food  220.5
Store 2  Naaya   Kitty Litter  120.5

In [60]:

df['Name'][df['Cost']>70]


Store 1    Rohit
Store 2    Naaya
Name: Name, dtype: object

In [62]:
purchase_1 = pd.Series({'Name': 'Rohit',  'Item Purchased': 'Dog Food', 'Cost': 220.50})

purchase_2 = pd.Series({'Name': 'Naaya',  'Item Purchased': 'Kitty Litter', 'Cost': 120.50})

purchase_3 = pd.Series({'Name': 'Vinod',  'Item Purchased': 'Bird See', 'Cost': 50.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 2', 'Store 3'])
df

Name Item Purchased   Cost
Store 1  Rohit       Dog Food  220.5
Store 2  Naaya   Kitty Litter  120.5
Store 3  Vinod       Bird See   50.0

In [63]:
 df['Item Purchased']



Store 1        Dog Food
Store 2    Kitty Litter
Store 3        Bird See
Name: Item Purchased, dtype: object

In [64]:
np.array([[0],[0]]) + 5

array([[5],
       [5]])