In [7]:
import numpy as np

In [2]:
#matrix operstion

In [5]:
x = np.matrix('1,2,3;40,50,6;,7,80,9')
x

matrix([[ 1,  2,  3],
        [40, 50,  6],
        [ 7, 80,  9]])

In [6]:
det_x = np.linalg.det(x)

In [8]:
det_x

7884.0

In [9]:
np.linalg.matrix_rank(x)

3

In [10]:
np.linalg.inv(x)

matrix([[-0.00380518,  0.0281583 , -0.01750381],
        [-0.04033486, -0.00152207,  0.01445967],
        [ 0.36149163, -0.00837139, -0.00380518]])

In [11]:
A = np.matrix('3,1,2;4,2,5,;6,7,8')
A

matrix([[3, 1, 2],
        [4, 2, 5],
        [6, 7, 8]])

In [14]:
B = np.matrix('2,-1,3').transpose()
B

matrix([[ 2],
        [-1],
        [ 3]])

In [15]:
sol = np.linalg.solve(A,B)
sol

matrix([[ 1.51851852],
        [ 1.37037037],
        [-1.96296296]])

In [16]:
#axis logic

In [18]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr1.sum()

78

In [20]:
arr1.sum(axis=1)

array([10, 26, 42])

In [21]:
#file handeling in numpy

In [22]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.savetxt('a.csv',a)

In [24]:
pwd

'C:\\Users\\hp\\jupyter'

In [25]:
np.savetxt('a.csv',a,delimiter=',')

In [28]:
np.loadtxt('a.csv',delimiter=',')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [29]:
np.save('data.npy',a)

In [31]:
np.load('data.npy')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.savez('both.npz',a,arr)

In [36]:
d = np.load('both.npz')

In [37]:
d.files

['arr_0', 'arr_1']

In [38]:
d.files[0]

'arr_0'

In [39]:
d[d.files[0]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
d[d.files[1]]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# panda series

In [9]:
import pandas as pd

In [44]:
#using list 

In [45]:
mylist = [100,200,300]

In [46]:
pd.Series(mylist)

0    100
1    200
2    300
dtype: int64

In [47]:
labels = ['A','B','C']

In [49]:
pd.Series(mylist,labels)

A    100
B    200
C    300
dtype: int64

In [50]:
# using numpy array

In [51]:
arr = np.array([100,200,300])

In [52]:
pd.Series(arr,labels)

A    100
B    200
C    300
dtype: int32

In [55]:
s1 = pd.Series(arr,labels,name='Meathod2')
s1

A    100
B    200
C    300
Name: Meathod2, dtype: int32

In [56]:
# using dictionary

In [10]:
dict = {'A':100,'B':200,'C':300}
z1 = pd.Series(dict)
z1

A    100
B    200
C    300
dtype: int64

In [11]:
z2 = pd.Series([10,20,30,40],'A B C D'.split())
z2

A    10
B    20
C    30
D    40
dtype: int64

In [12]:
'A B C D'.split()

['A', 'B', 'C', 'D']

In [13]:
z1+z2

A    110.0
B    220.0
C    330.0
D      NaN
dtype: float64