In [1]:
import numpy as np

##### Numpy array using List

In [2]:
x = [1,2,3,4,5,6]
x

[1, 2, 3, 4, 5, 6]

In [3]:
type(x)

list

In [4]:
np.array(x)

array([1, 2, 3, 4, 5, 6])

In [5]:
y = np.array([1,2,3,'NIELIT',4.6])
y

array(['1', '2', '3', 'NIELIT', '4.6'], dtype='<U11')

##### Numpy array using Tuple

In [6]:
x1 = (1,2,3,4,5,6)
x1

(1, 2, 3, 4, 5, 6)

In [7]:
type(x1)

tuple

In [8]:
np.array(x1)

array([1, 2, 3, 4, 5, 6])

### Linspace

In [12]:
y = np.linspace(start=0,stop=20,num=10,retstep=True)

In [13]:
y

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

In [11]:
np.linspace(start=0,stop=20,num=10,endpoint=False)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [14]:
np.linspace(start=0,stop=20,num=10,endpoint=False)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

##### Arange

In [15]:
np.arange(start=1,stop=20,step=2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Reshaping

In [16]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Random Number Generation

In [19]:
np.random.rand(5)

array([0.51384316, 0.99265044, 0.92780267, 0.60867178, 0.36441682])

In [20]:
np.random.rand(5,4)

array([[0.46899998, 0.57833278, 0.95067634, 0.16981638],
       [0.76105724, 0.99831801, 0.24371688, 0.40193396],
       [0.91600135, 0.00405676, 0.366075  , 0.10480294],
       [0.35604604, 0.52844564, 0.90153377, 0.36363412],
       [0.81376739, 0.61780949, 0.24836176, 0.22123906]])

In [21]:
np.random.randn(5,4)

array([[-1.3348633 ,  0.09608416,  1.90884811,  2.8940458 ],
       [-0.50934631,  1.28438505,  0.09114329, -0.38371029],
       [ 1.13933461,  0.25114266,  1.3894824 ,  0.23447841],
       [-1.11760945, -0.35065141, -2.39857072,  0.51811665],
       [-0.22514452, -1.26814758, -0.10401693,  0.59445507]])

### randint

In [22]:
np.random.randint(low=1,high=100)

33

In [23]:
np.random.randint(low=1,high=100,size=20)

array([81, 27,  6, 62, 73, 52, 73, 27, 75, 15, 69,  6, 31, 93, 94, 30, 27,
       93, 72, 68])

### Seed

In [24]:
np.random.seed(34)
np.random.rand(5)

array([0.03856168, 0.78010046, 0.09270376, 0.63289269, 0.01389085])

In [27]:
np.random.seed(34)
np.random.rand(5)

array([0.03856168, 0.78010046, 0.09270376, 0.63289269, 0.01389085])

In [25]:
np.random.seed(40)
np.random.rand(5)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518, 0.45035059])

In [26]:
np.random.rand(5)

array([0.30391231, 0.52639952, 0.62381221, 0.77677546, 0.68624165])

In [28]:
#this is my new code
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## this is