In [1]:
import numpy as np


In [2]:
# numpy array using list

In [3]:
x = [1,2,3,4,5]

In [4]:
x

[1, 2, 3, 4, 5]

In [5]:
type(x)

list

In [6]:
np.array(x)

array([1, 2, 3, 4, 5])

In [8]:
y = np.array([1,2,3,4,5,'nielit'])
y

array(['1', '2', '3', '4', '5', 'nielit'], dtype='<U11')

In [9]:
# numpy array using tuple

In [11]:
a = (1,2,3,4,5)
a

(1, 2, 3, 4, 5)

In [14]:
q = np.linspace(start=0,stop=20,num=10,endpoint=False)
q

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [15]:
q1 = np.linspace(start=0,stop=20,num=10,retstep=True)
q1

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

In [17]:
np.arange(start=1,stop=20,step=2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
d = np.array([0,1,2,3,4,5,6,7,8,9])
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
d.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
np.random.rand(5)

array([0.56123284, 0.16433504, 0.15591775, 0.07189773, 0.29515637])

In [25]:
np.random.rand(5,4)

array([[0.76419317, 0.81422611, 0.35642972, 0.72853919],
       [0.90292874, 0.62751309, 0.4600783 , 0.94632048],
       [0.40391763, 0.52724122, 0.85611128, 0.97282442],
       [0.21195146, 0.186522  , 0.07847301, 0.7381327 ],
       [0.09174758, 0.65518088, 0.03036137, 0.68325414]])

In [26]:
np.random.randn(5,4)

array([[-0.17111963,  0.34161069, -0.93483643,  0.50451256],
       [ 0.23123682,  2.10953204, -1.69803968,  0.17980885],
       [ 0.6507028 , -2.00624189, -0.9374181 , -2.65902676],
       [-0.11151876, -0.06522709, -0.72097903, -1.12008532],
       [-0.63282236, -0.05411859,  2.01221223, -0.04163643]])

In [29]:
np.random.randint(low=1,high=100)

87

In [30]:
np.random.randint(low=1,high=100,size=20)

array([43, 93, 43, 30, 19, 59,  7, 23, 98, 78, 68, 45, 25, 62, 94, 76, 24,
       63, 57, 38])

In [31]:
np.random.seed(34)
np.random.rand(5)

array([0.03856168, 0.78010046, 0.09270376, 0.63289269, 0.01389085])

In [32]:
np.random.seed(40)
np.random.rand(5)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518, 0.45035059])