In [12]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [2]:
import numpy as np

In [11]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [4]:
#conditional selection

In [7]:
arr = np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
boo_arr = arr>4
boo_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
arr[boo_arr]

array([5, 6, 7, 8, 9])

In [13]:
arr[arr>4]

array([5, 6, 7, 8, 9])

In [14]:
#arthematic

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr + arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
arr * arr


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [18]:
arr / arr

<ipython-input-18-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [19]:
1/arr

<ipython-input-19-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [22]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [21]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [24]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [25]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [26]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [27]:
#list vs numpy

In [28]:
size = 100

In [29]:
x1 = range(size)
y1 = range(size)

In [31]:
%%timeit
for i in range(size):
    x1[i]*y1[i]

47.9 µs ± 2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [32]:
x2 = np.arange(size)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [33]:
y2 = np.arange(size)
y2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
%%timeit
x2*y2

1.06 µs ± 39.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [35]:
# append

In [36]:
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a_row = np.append(a,[[21,22,23]], axis=0)
a_row

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [21, 22, 23]])

In [39]:
a_col = np.array([[32,33,34]]).reshape(3,1)
a_col

array([[32],
       [33],
       [34]])

In [41]:
a_coll = np.append(a,a_col,axis=1)
a_coll

array([[ 1,  2,  3, 32],
       [ 4,  5,  6, 33],
       [ 7,  8,  9, 34]])

In [42]:
#insert

In [43]:
b = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.insert(b,1,[15,13,12],axis=0)

array([[ 1,  2,  3],
       [15, 13, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [45]:
b_ins = np.insert(b,1,[15,13,12],axis=1)
b_ins

array([[ 1, 15,  2,  3],
       [ 4, 13,  5,  6],
       [ 7, 12,  8,  9]])

In [46]:
#matrix

In [52]:
x = np.matrix('1,2,3;4,5,6;7,8,9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [53]:
x.shape

(3, 3)