In [1]:
import numpy as np

### Matrix Operation

In [2]:
x = np.matrix('1,2,3;40,50,6;7,80,9')
x

matrix([[ 1,  2,  3],
        [40, 50,  6],
        [ 7, 80,  9]])

In [3]:
det_x = np.linalg.det(x)
det_x

7884.0

In [4]:
np.linalg.matrix_rank(x)

3

In [5]:
x_inv = np.linalg.inv(x)

In [6]:
x_inv

matrix([[-0.00380518,  0.0281583 , -0.01750381],
        [-0.04033486, -0.00152207,  0.01445967],
        [ 0.36149163, -0.00837139, -0.00380518]])

In [7]:
A = np.matrix('3,1,2;4,2,5;6,7,8')
A

matrix([[3, 1, 2],
        [4, 2, 5],
        [6, 7, 8]])

In [8]:
B = np.matrix('2,-1,3').transpose()

In [9]:
B

matrix([[ 2],
        [-1],
        [ 3]])

In [10]:
sol = np.linalg.solve(A,B)
sol

matrix([[ 1.51851852],
        [ 1.37037037],
        [-1.96296296]])

### Axis Logic

In [11]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
#[(1+5+9),(2+6+10),(3+7+10),(4+8+12)]
arr1.sum(axis=0)

array([15, 18, 21, 24])

In [13]:
#[(1+2+3+4),(5+6+7+8),(9+10+11+12)]
arr1.sum(axis=1)


array([10, 26, 42])

In [14]:
arr1.sum()

78

### File Handeling in Numpy

In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.savetxt('a.csv',a,delimiter=',')

In [17]:
np.loadtxt('a.csv',delimiter=',')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [18]:
np.save('data.npy',a)

In [19]:
np.load('data.npy')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.savez('both.npz',a,arr)

In [23]:
d = np.load('both.npz')

In [24]:
d.files

['arr_0', 'arr_1']

In [25]:
d[d.files[0]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
d[d.files[1]]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Example nan & inf

In [2]:
3==3

True

In [3]:
np.nan == np.nan

False

In [4]:
np.inf==np.inf

True

In [5]:
None==None

True

In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a.dtype

dtype('int32')

In [8]:
type(np.nan)

float

In [9]:
a = a.astype('float')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
a[0][0] = np.nan

In [11]:
a[1][1] = np.inf

In [12]:
a

array([[nan,  2.,  3.],
       [ 4., inf,  6.],
       [ 7.,  8.,  9.]])

In [13]:
np.isinf(a)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [14]:
np.isnan(a)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [15]:
flag = np.isinf(a)|np.isnan(a)

In [16]:
flag

array([[ True, False, False],
       [False,  True, False],
       [False, False, False]])

### Data Cleaning 

In [17]:
a[flag]

array([nan, inf])

In [18]:
a[flag]=0

In [19]:
a

array([[0., 2., 3.],
       [4., 0., 6.],
       [7., 8., 9.]])

### &&&&&